name: rick_and_morty_app
description: "Test task"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  dio: ^5.8.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  intl: ^0.20.2
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/placeholder.png

